import { Product } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Bihar Heritage Tee',
    price: 599,
    originalPrice: 899,
    image: '/products/maroon-heritage.png',
    images: ['/products/maroon-heritage.png', '/products/navy-culture.png', '/products/terracotta-classic.png', '/products/black-essentials.png'],
    category: 'classic',
    featured: true,
    description: 'A timeless tee celebrating Bihari heritage with elegant minimal design',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Maroon', 'Navy', 'Black'],
    fabric: '100% Cotton',
    inStock: true,
    stockQuantity: 50,
    new: false,
  },
  {
    id: '2',
    name: 'Funky Patna Vibes Tee',
    price: 649,
    originalPrice: 999,
    image: '/products/navy-culture.png',
    images: ['/products/navy-culture.png', '/products/maroon-heritage.png', '/products/terracotta-classic.png', '/products/olive-roots.png'],
    category: 'funky',
    featured: true,
    description: 'Bold and vibrant design capturing the essence of Patna city life',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White', 'Black'],
    fabric: '100% Cotton',
    inStock: true,
    stockQuantity: 50,
    new: true,
  },
  {
    id: '3',
    name: 'CSK Cricket Fan Tee',
    price: 699,
    originalPrice: 999,
    image: '/products/terracotta-classic.png',
    images: ['/products/terracotta-classic.png', '/products/navy-culture.png', '/products/maroon-heritage.png', '/products/black-essentials.png'],
    category: 'ipl',
    featured: false,
    description: 'Show your cricket passion with this premium CSK inspired tee',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Yellow', 'Blue'],
    fabric: 'Polyester Blend',
    inStock: true,
    stockQuantity: 50,
    new: false,
  },
  {
    id: '4',
    name: 'Minimal Black Statement Tee',
    price: 549,
    originalPrice: 799,
    image: '/products/black-essentials.png',
    images: ['/products/black-essentials.png', '/products/olive-roots.png', '/products/offwhite-premium.png', '/products/navy-culture.png'],
    category: 'minimal',
    featured: false,
    description: 'Pure elegance with minimal printing for the modern minimalist',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White'],
    fabric: '100% Cotton',
    inStock: true,
    stockQuantity: 50,
    new: false,
  },
  {
    id: '5',
    name: 'IPL Trending Combo Pack',
    price: 1299,
    originalPrice: 1999,
    image: '/products/olive-roots.png',
    images: ['/products/olive-roots.png', '/products/terracotta-classic.png', '/products/navy-culture.png', '/products/maroon-heritage.png'],
    category: 'ipl',
    featured: true,
    description: 'Triple pack of premium IPL collection tees at unbeatable price',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Multi'],
    fabric: '100% Cotton',
    inStock: true,
    stockQuantity: 50,
    new: true,
  },
  {
    id: '6',
    name: 'Festival Celebration Tee',
    price: 599,
    originalPrice: 899,
    image: '/products/offwhite-premium.png',
    images: ['/products/offwhite-premium.png', '/products/maroon-heritage.png', '/products/navy-culture.png', '/products/black-essentials.png'],
    category: 'trending',
    featured: false,
    description: 'Celebrate Bihar festivals in style with this vibrant design',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Off White', 'Yellow'],
    fabric: '100% Cotton',
    inStock: true,
    stockQuantity: 50,
    new: false,
  },
  {
    id: '7',
    name: 'Urban Bihar Streetwear',
    price: 749,
    originalPrice: 1099,
    image: '/products/navy-culture.png',
    images: ['/products/navy-culture.png', '/products/black-essentials.png', '/products/olive-roots.png', '/products/terracotta-classic.png'],
    category: 'trending',
    featured: false,
    description: 'Contemporary streetwear meets Bihari cultural pride',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'Black'],
    fabric: 'Heavy Cotton',
    inStock: true,
    stockQuantity: 50,
    new: true,
  },
  {
    id: '8',
    name: 'Premium Heritage Collection',
    price: 899,
    originalPrice: 1299,
    image: '/products/terracotta-classic.png',
    images: ['/products/terracotta-classic.png', '/products/maroon-heritage.png', '/products/navy-culture.png', '/products/offwhite-premium.png'],
    category: 'classic',
    featured: true,
    description: 'Limited edition premium collection celebrating Bihari artisan crafts',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Terracotta', 'Beige'],
    fabric: 'Premium Cotton',
    inStock: true,
    stockQuantity: 50,
    new: false,
  },
]


export const mockOffers = [
  {
    id: '1',
    title: 'Combo T-Shirts',
    price: 999,
    originalPrice: 1499,
    image: '/products/maroon-heritage.png',
    description: '3 Premium Tees at Special Price',
  },
  {
    id: '2',
    title: 'Summer Special',
    price: 399,
    originalPrice: 599,
    image: '/products/offwhite-premium.png',
    description: 'Beat the Heat with Summer Collection',
  },
  {
    id: '3',
    title: 'College Fest Pack',
    price: 1199,
    originalPrice: 1799,
    image: '/products/black-essentials.png',
    description: 'Perfect for Campus Events',
  },
  {
    id: '4',
    title: 'IPL Fan Pack',
    price: 1499,
    originalPrice: 2199,
    image: '/products/terracotta-classic.png',
    description: 'Show Your Cricket Spirit',
  },
  {
    id: '5',
    title: 'Minimal Black Pack',
    price: 1099,
    originalPrice: 1699,
    image: '/products/olive-roots.png',
    description: 'Premium Elegance Collection',
  },
]

export const mockOrders = [
  {
    id: 'ORD001',
    customerName: 'Raj Kumar',
    customerEmail: 'raj@example.com',
    items: [
      { productId: '1', quantity: 2, size: 'M' },
      { productId: '3', quantity: 1, size: 'L' },
    ],
    total: 1897,
    status: 'delivered',
    createdAt: new Date('2024-12-01'),
  },
  {
    id: 'ORD002',
    customerName: 'Priya Singh',
    customerEmail: 'priya@example.com',
    items: [
      { productId: '2', quantity: 1, size: 'S' },
      { productId: '5', quantity: 1, size: 'M' },
    ],
    total: 1348,
    status: 'processing',
    createdAt: new Date('2024-12-10'),
  },
]

export const mockEnquiries = [
  {
    id: 'ENQ001',
    businessName: 'Tech Startup XYZ',
    contactPerson: 'Amresh Singh',
    phone: '+91-9876543210',
    email: 'amresh@techxyz.com',
    quantity: 500,
    status: 'pending',
    createdAt: new Date('2024-12-05'),
    message: 'Looking for bulk order of 500 tees for our annual event.',
  },
  {
    id: 'ENQ002',
    businessName: 'Local Fashion Boutique',
    contactPerson: 'Shreya Yadav',
    phone: '+91-9876543211',
    email: 'shreya@boutique.com',
    quantity: 200,
    status: 'quoted',
    createdAt: new Date('2024-12-08'),
    message: 'Interested in a long-term partnership for stocking your products.',
  },
]

export const mockUsers = [
  {
    id: '1',
    name: 'Akash Verma',
    email: 'akash@example.com',
    createdAt: new Date('2024-11-15'),
    orderCount: 3,
  },
  {
    id: '2',
    name: 'Meera Patel',
    email: 'meera@example.com',
    createdAt: new Date('2024-11-20'),
    orderCount: 1,
  },
]
